### ISSUE TITLE
Azure build fails at Install Node.js

### ISSUE THREAD

**Issue by KuraiAndras** [openupm/openupm#137] opened 2020-04-01 20:24 UTC
I have updated [UnityExtensions.DependencyInjection](https://github.com/KuraiAndras/UnityExtensions.DependencyInjection) from 2.0.0 to 3.0.0, and it seems the pipeline [failed](https://dev.azure.com/openupm/openupm/_build/results?buildId=3400&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=b29e13d3-e02a-52ad-12be-2be01aa38374).

Can you tell me if something went wrong on my end or it's a bug in the pipeline?

**Comment by favoyang** [comment] 2020-04-02 05:21
@KuraiAndras,

Thanks for reporting the issue, and it's been fixed now. I will check why the pipeline didn't rebuild it automatically later.

**Closed** 2020-04-02 11:34 UTC

**Comment by favoyang** [comment] 2020-04-02 11:43
The issue is caused by the limited ability to process the pipeline build message to find out the actual failure reason. The Azure pipeline API is not very smart to figure out the failed step, so instead of pulling all log steps one by one, I simply check the final publishing task, and treat all other failure as "unknown"., which will not trigger a rebuild. But as a second thought, I changed it, so "unknown" failure reason will trigger a rebuild now.
