### ISSUE TITLE
Ignore or use readme-titles

### ISSUE THREAD

**Issue by ComradeVanti** [openupm/openupm#3320] opened 2022-09-10 17:42 UTC
#### Feature category

Website: improve the way to browse or discover packages.

#### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/31240807/189495320-b8b94c9a-4438-4fb5-9656-d4d22d9c947c.png)
As you can see in this example my readme starts with a h1 header with the package name, but this header is not rendered correctly. 

#### How should this be implemented in your opinion?

I would expect for the website to either not display the h1 header or to use the h1 header as the displayed title instead of the packages name.

#### Are you a regular backer or sponsor at [patreon.com/openupm](https://www.patreon.com/openupm)?

Hell yeah

#### Are you willing to work on this yourself?

No sorry

**Comment by favoyang** [comment] 2022-09-12 14:18
I think this is caused by a hidden unicode `\ufeff` (bom of utf16 or utf32). Which is unnecessary for utf8 encoded markdown file.

You can remove the "red dot' from the GitHub editor: https://github.com/ComradeVanti/UnityRectConstraints/edit/main/README.md

![image](https://user-images.githubusercontent.com/125390/189677198-033b7904-2382-4ccb-b5cf-47222f34f694.png)

Then the build pipelines will fetch the updated README.md and your H1 shall show up (takes about 1h after your commit).

If it works please close the issue. Thank you.

**Comment by ComradeVanti** [comment] 2022-09-13 06:15
Hey, will fix. Seems like Rider creates md files with this BOM by default. Maybe skipping any leading BOM characters would be a good idea when displaying the readme, just to be safe?

**Comment by ComradeVanti** [comment] 2022-09-13 06:16
Most markdown renderers, like the regular Github one or the one in Rider handle this case by ignoring the character, it seems

**Closed** 2023-02-22 11:32 UTC
